services:
  - type: web
    name: koffee-gbp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SERP_API_KEY
        value: 05746604c702ad7a4456cbbf34ae1e356f6ed6b146a5f85f0ac9cdfb8a71f15e
